### ISSUE TITLE
Departure to Mt. Lebanon does not work

### ISSUE THREAD

**Issue by ldt9** [itsmekhalidb/PlanesOverTrains#27]
```
Exception in thread Thread-1839:
Traceback (most recent call last):
  File "C:\Users\14845\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\14845\AppData\Local\Programs\Python\Python39\lib\threading.py", line 1299, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\14845\Documents\PlanesOverTrains_V2\track_model\track_model.py", line 203, in update
    self._TrainModels.train_apis[index].current_block = self.update_current_block(self._TrainModels.train_apis[index])
  File "C:\Users\14845\Documents\PlanesOverTrains_V2\track_model\track_model.py", line 225, in update_current_block
    self._switch_to = self.block_data.get_switch_list(train.line)
  File "C:\Users\14845\Documents\PlanesOverTrains_V2\track_model\block_info.py", line 130, in get_switch_list
    return self.switch_list.get(line, {})
AttributeError: 'block_info' object has no attribute 'switch_list'
```

We need to add a switch_list attribute to the block info for track_model.

@itsmekhalidb Please define what you want this to look like.

**Comment by ldt9** [comment]
Increased Default Time for departures so that it doesn't try to go back to the future
